name: flutter_application_1
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0  # Updated firebase_core version
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/screen1.png
    - images/screen2.png
    - images/screen3.png
    - images/burger.png
    - images/ice-cream.png
    - images/pizza.png
    - images/salad.png
    - images/salad2.png
    - images/salad3.png
    - images/salad4.png
